//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDTRACK_DAL.Models
{
    using System;
    
    public partial class AuditUserDetails
    {
        public long AuditID { get; set; }
        public Nullable<System.DateTime> AuditTimeStamp { get; set; }
        public string EventDescription { get; set; }
        public string By { get; set; }
        public string For { get; set; }
        public string ForSupplierCode { get; set; }
        public string ForSupplierName { get; set; }
        public string BySupplierCode { get; set; }
        public string BySupplierName { get; set; }
        public Nullable<long> UserID { get; set; }
        public Nullable<long> AffectedUserID { get; set; }
    }
}
