//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDTRACK_DAL.Models
{
    using System;
    
    public partial class SecurityQuestions
    {
        public long Id { get; set; }
        public string Question { get; set; }
    }
}
